/**
 * RoutingDemo
 *
 * Example of a routing workflow that classifies input and routes to specialized agents:
 * 1. Classifier - Classify the query type
 * 2. Route to appropriate specialist:
 *    - Technical Agent (for technical questions)
 *    - Business Agent (for business questions)
 *    - General Agent (for general questions)
 * 3. Response Formatting - Format the response
 */

import { WorkflowExecutionState, WorkflowStep } from '../WorkflowCard';

/**
 * State update callback
 */
type StateUpdateCallback = (state: Partial<WorkflowExecutionState>) => void;

/**
 * Simulate routing workflow execution
 */
export async function runRoutingDemo(
  onStateUpdate: StateUpdateCallback
): Promise<string> {
  const steps: WorkflowStep[] = [
    {
      name: 'Query Classifier',
      description: 'Analyzing query to determine the appropriate specialist',
      status: 'pending',
    },
    {
      name: 'Specialist Agent',
      description: 'Processing query with specialized knowledge',
      status: 'pending',
    },
    {
      name: 'Response Formatter',
      description: 'Formatting the response for optimal presentation',
      status: 'pending',
    },
  ];

  // Initialize state
  onStateUpdate({
    status: 'running',
    steps: [...steps],
    currentStep: 0,
  });

  const startTime = Date.now();

  // Step 1: Classify the query
  const classifierStep = steps[0];
  classifierStep.status = 'running';
  classifierStep.startTime = Date.now();

  onStateUpdate({
    steps: [...steps],
    currentStep: 0,
  });

  await sleep(1200);

  // Randomly choose a query type for demo
  const queryTypes = ['technical', 'business', 'general'];
  const selectedType = queryTypes[Math.floor(Math.random() * queryTypes.length)];

  classifierStep.status = 'completed';
  classifierStep.output = `Query classified as: ${selectedType.toUpperCase()}. Confidence: 92%. Routing to ${selectedType} specialist.`;
  classifierStep.endTime = Date.now();

  onStateUpdate({
    steps: [...steps],
  });

  await sleep(500);

  // Step 2: Route to specialist
  const specialistStep = steps[1];
  specialistStep.name = `${selectedType.charAt(0).toUpperCase() + selectedType.slice(1)} Specialist`;
  specialistStep.status = 'running';
  specialistStep.startTime = Date.now();

  onStateUpdate({
    steps: [...steps],
    currentStep: 1,
  });

  await sleep(2000);

  // Generate specialist response
  let specialistOutput = '';
  switch (selectedType) {
    case 'technical':
      specialistOutput =
        'Technical Analysis: AI workflows use orchestration patterns to coordinate multiple agents. Implementation requires careful consideration of async execution, state management, and error handling. Recommended approach: Start with sequential workflows, then add parallel execution for independent tasks.';
      break;
    case 'business':
      specialistOutput =
        'Business Analysis: AI workflows deliver 40-60% efficiency improvements in complex processes. ROI typically achieved within 3-6 months. Key benefits: reduced manual work, improved accuracy, scalability. Success factors: clear use case definition, stakeholder alignment, and iterative implementation.';
      break;
    case 'general':
      specialistOutput =
        'General Overview: AI workflows are structured patterns for coordinating AI agents to solve complex problems. They provide reliable, scalable solutions for tasks that previously required extensive manual effort. Common applications include research automation, content generation, and data analysis.';
      break;
  }

  specialistStep.status = 'completed';
  specialistStep.output = specialistOutput;
  specialistStep.endTime = Date.now();

  onStateUpdate({
    steps: [...steps],
  });

  await sleep(500);

  // Step 3: Format response
  const formatterStep = steps[2];
  formatterStep.status = 'running';
  formatterStep.startTime = Date.now();

  onStateUpdate({
    steps: [...steps],
    currentStep: 2,
  });

  await sleep(1000);

  formatterStep.status = 'completed';
  formatterStep.output = `Formatted Response:\n\nQuery Type: ${selectedType.toUpperCase()}\n\n${specialistOutput}\n\nNote: This response was generated by our ${selectedType} specialist based on query classification. For further assistance, please specify your question type or ask a follow-up.`;
  formatterStep.endTime = Date.now();

  onStateUpdate({
    steps: [...steps],
  });

  const totalTime = Date.now() - startTime;
  const finalResult = formatterStep.output || '';

  // Mark as completed
  onStateUpdate({
    status: 'completed',
    result: finalResult,
    totalTime,
  });

  return finalResult;
}

/**
 * Sleep helper
 */
function sleep(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms));
}
